### ISSUE TITLE
ctrl-enter (insert line below, insert line above) in middle of line not adding `///`

### ISSUE THREAD

**Issue by WebFreak001** [kasecato/vscode-docomment#98]
When having
```cs
/// <summary>
/// Hello| world
/// </summary>
```

pressing ctrl-enter or ctrl-shift-enter (Insert line below, insert line above) at the indicated location will insert a new line but not insert any `///`.

With insert line below it will enter it if the cursor was at the very right, with insert line above it seems like it never inserts it.

**Comment by kasecato** [comment]
![#98](https://user-images.githubusercontent.com/10364603/88353109-3ddef880-cd97-11ea-8208-54491cb62627.gif)

**Comment by kasecato** [comment]
@WebFreak001  Many thank you for your but report. I just fixed this issue on [v0.1.15](https://marketplace.visualstudio.com/items?itemName=k--kato.docomment). Please check it 👍

**Comment by WebFreak001** [comment]
ctrl-enter in the middle of the line is still broken and also getting error messages in the developer tools now:
```
[[object Object]]Cannot read property 'text' of undefined

TypeError: Cannot read property 'text' of undefined
	at DocommentDomainCSharp.IsTriggerDocomment (c:\Users\jurzitza\.vscode\extensions\k--kato.docomment-0.1.14\out\src\Domain\Lang\DocommentDomainCSharp.js:24:39)
	at DocommentDomainCSharp.Execute (c:\Users\jurzitza\.vscode\extensions\k--kato.docomment-0.1.14\out\src\Domain\DocommentDomain.js:21:19)
	at DocommentControllerCSharp._onEvent (c:\Users\jurzitza\.vscode\extensions\k--kato.docomment-0.1.14\out\src\Controller\DocommentController.js:55:31)
	at DocommentControllerCSharp.<anonymous> (c:\Users\jurzitza\.vscode\extensions\k--kato.docomment-0.1.14\out\src\Controller\DocommentController.js:19:22)
```

![cursor in middle of line](https://i.imgur.com/dI8odz9.png)
![documentation comment not inserted](https://i.imgur.com/aPac6jC.png)

**Comment by WebFreak001** [comment]
I'm getting exceptions while typing in 0.1.15:
```
ypeError: Cannot read property 'text' of undefined
	at DocommentDomainCSharp.IsTriggerDocomment (c:\Users\jurzitza\.vscode\extensions\k--kato.docomment-0.1.15\out\src\Domain\Lang\DocommentDomainCSharp.js:30:39)
	at DocommentDomainCSharp.Execute (c:\Users\jurzitza\.vscode\extensions\k--kato.docomment-0.1.15\out\src\Domain\DocommentDomain.js:23:19)
	at DocommentControllerCSharp._onEvent (c:\Users\jurzitza\.vscode\extensions\k--kato.docomment-0.1.15\out\src\Controller\DocommentController.js:55:31)
	at DocommentControllerCSharp.<anonymous> (c:\Users\jurzitza\.vscode\extensions\k--kato.docomment-0.1.15\out\src\Controller\DocommentController.js:19:22)
```

Ctrl-Enter is still broken:
![cursor in middle of line](https://i.imgur.com/dI8odz9.png)
![ctrl enter not inserting doc comment](https://i.imgur.com/aPac6jC.png)

Ctrl-Shift-Enter seems to work though.

**Comment by kasecato** [comment]
Thank you @WebFreak001 . I reproduced it. I just fixed it on v0.1.16. I'm sorry to keep asking you to do this, but please check it.

**Comment by WebFreak001** [comment]
seems to works fine now

Still getting the stacktraces in the developer tools which you might want to fix eventually though.

**Comment by kasecato** [comment]
@WebFreak001 Sorry for reopening this issue. I reverted this because of #108 . Currently,  we can't use `ctrl+shift+enter`. I'll fix it until this weekend.
